version: "3.11"

services:
   postgres:
      container_name: cats.db
      image: postgres:16-alpine
      restart: unless-stopped
      ports:
         - "5432:5432"
      environment:
         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
         POSTGRES_USER: ${POSTGRES_USER}
         POSTGRES_DB: ${POSTGRES_DB}
      volumes:
         - postgres-data:/var/lib/postgresql/data:rw
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
         interval: 10s
         timeout: 5s
         retries: 5
         start_period: 30s

   api:
      container_name: cats.api
      build: .
      restart: unless-stopped
      ports:
         - "8000:8000"
      env_file: .env
      depends_on:
         postgres:
            condition: service_healthy

volumes:
   postgres-data: {}